### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive-Launcher#1]
Right now on windows the default electron icon is used and on linux there's no icon.

That should be fixed.
Also if someone could create a .ico executable icon (and a .png for linux) of the thrive logo that would be great.

**Comment by crodnu** [comment]
It should also be different from the one in the game executable

**Comment by hhyyrylainen** [comment]
The first iteration of the icon (which gets slightly blurry in the bottom right corner when really small) is in

**Comment by hhyyrylainen** [comment]
This is an issue about the graphics asset. https://github.com/Revolutionary-Games/Thrive-Launcher/issues/5 is an issue about wrong icon being shown and also the wrong name.

**Comment by hhyyrylainen** [comment]
This should work currently.
