### ISSUE TITLE
Keyboard Lagging

### ISSUE THREAD

**Issue by Anth0rx** [Revolutionary-Games/Thrive-Launcher#100]
I experience enormous keyboard lagging when playing Thrive. After some time holding WASD to move there is a massive lag when releasing the key. It keeps moving for more than a minute and I am not able to interrupt moving.

**Comment by hhyyrylainen** [comment]
This sounds more like an issue with the game, than the launcher. Please report Thrive issues here: https://github.com/Revolutionary-Games/Thrive/issues

**Comment by Anth0rx** [comment]
Oh sure, sorry.
