### ISSUE TITLE
OSX installer does not function

### ISSUE THREAD

**Issue by typographitext** [Revolutionary-Games/Thrive-Launcher#117]
I'ved tried 3 times with the same result each time. After running the installing on OSX, you get this error:

Playing Thrive 0.5.3.1
Unpacking failed, File 'Thrive_0.5.3.1_mac_osx.zip' is invalid? Error: Unpacker exited with code: null, message: dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin Referenced from: /Applications/Thrive Launcher.app/Contents/Resources/app.asar.unpacked/tools/7zip/7za_mac (which was built for Mac OS X 10.15) Expected in: /usr/lib/libSystem.B.dylib dyld: Symbol not found: ____chkstk_darwin Referenced from: /Applications/Thrive Launcher.app/Contents/Resources/app.asar.unpacked/tools/7zip/7za_mac (which was built for Mac OS X 10.15) Expected in: /usr/lib/libSystem.B.dylib

To try redownloading delete '/var/folders/rj/rzv7bm610397jr8r533f81lw0000gn/T/Revolutionary-Games-Launcher/Thrive_0.5.3.1_mac_osx.zip'

**Comment by hhyyrylainen** [comment]
@Nunez2196 could you take a look at this? Might be some OS version kind of problem with the packaged in 7za version.
If it doesn't already function like this, I think we should consider it: on mac prefer the system installed 7za, and on the unpack error suggestion handler (https://github.com/Revolutionary-Games/Thrive-Launcher/blob/master/src/error_suggestions.js), add `dyld: lazy symbol binding failed` to suggest using homebrew to install `p7zip`

**Comment by hhyyrylainen** [comment]
I've now got 2 test macs of my own, both running Monterey (intel and m1) and it works fine there. So I'll conclude that this problem is only with older mac OS versions, and with Big Sur being the oldest still supported by Apple, I'll close this as probably fine now.
