### ISSUE TITLE
Allow managing installed versions

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive-Launcher#12]
Allow deleting installed versions and the zips that are downloaded to let users get back diskspace.
~~Also the installed versions should be installed to the user's home folder in some suitable location, perhaps some that can also be used for save data for thrive.~~ This is already done.

**Comment by Themayu** [comment]
On Windows, would something like `%USERPROFILE%\Documents\My Games\Thrive\Versions` be an acceptable location for placing the installed versions?

For Linux, I'm guessing something like `~/.thrive/versions` would work? Or would it be better to have it not hidden by default?

**Comment by Themayu** [comment]
Or am I misunderstanding what is being said here?

> Also the installed versions should be installed to the user's home folder in some suitable location, perhaps some that can also be used for save data for thrive.

**Comment by hhyyrylainen** [comment]
It was outdated information. The install location is mentioned in this issue: https://github.com/Revolutionary-Games/Thrive-Launcher/issues/19
`C:/Users/YOURUSERNAMEHERE/AppData/Roaming/Revolutionary-Games/Launcher` or `~/.config/Revolutionary-Games/Launcher`

So this issue is as the title suggest for allowing the user to delete the versions of Thrive they have installed.

**Comment by Themayu** [comment]
Alright then.
