### ISSUE TITLE
The launcher was identified as "malicious" by Microsoft Defender SmartScreen.

### ISSUE THREAD

**Issue by somecat1996** [Revolutionary-Games/Thrive-Launcher#121]
Please note that you should only report bugs in the **launcher** here. If the launcher has successfully downloaded the game and started it, all problems after that, before the game is closed, are actually problems in the game itself. Those need to be reported to: https://github.com/Revolutionary-Games/Thrive/issues

**Describe the bug**
The launcher was identified as "malicious" by Microsoft Defender SmartScreen and Windows advised me not to install it.

**To Reproduce**
1. Download the launcher through Edge;
2. When the downloading completed, Edge showed a warning.

**Expected behavior**
The launcher should not be detected as malicious software by any antivirus software, should it?

**Screenshots**
![snipaste_20210504_110327](https://user-images.githubusercontent.com/22187615/116956661-600f8a80-acc8-11eb-9b17-6fea675ee52b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Launcher version 1.2.8

**Comment by hhyyrylainen** [comment]
This is not a bug, unless you consider us not paying microsoft over a hundred bucks a year to get a signing certificate to be a bug.
I make the Windows launcher builds with electron builder. Unless someone overwrites the build files on github or there's a supply chain attack with electron, the builds are safe.
