### ISSUE TITLE
Add link to the donations page

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive-Launcher#125]
Add a link to https://revolutionarygamesstudio.com/donate/ to the list of links in the launcher.

**Comment by mouadTaoussi** [comment]
Hello! which link are you talking about?
Can you explain me more about that issue?

**Comment by hhyyrylainen** [comment]
I mean the links shown when the user presses the "Links" button, those are defined in html here: 
https://github.com/Revolutionary-Games/Thrive-Launcher/blob/f69728ac36a8ff2a48b36bd551f9558636d8b83e/src/index.html#L152
