### ISSUE TITLE
Notifications get shown as electron.app.Thrive Launcher

### ISSUE THREAD

**Issue by FuJa0815** [Revolutionary-Games/Thrive-Launcher#136]
**Describe the bug**
The notifications shown have the app name as the title

**Expected behavior**
A propper title should show up

**Screenshots**
![image](https://user-images.githubusercontent.com/30809803/143479498-749c7d53-1a28-46f6-87be-2bb3a1b90188.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by hhyyrylainen** [comment]
Launcher 2.0 won't show these types of notifications.
