### ISSUE TITLE
Launcher file verify gets stuck on suse linux

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive-Launcher#137]
https://community.revolutionarygamesstudio.com/t/launcher-freeze-suse-linux-15-0/4030

Seems like consistently the launcher just fails to verify the downloaded game file on that specific linux distro for some reason.

Edit: update comment from original reporter:

> I just tested on SUSE 15.3, and it didn’t freeze. So it does seem like it’s related to 15.0 in some way.

**Comment by Doomsdayrs** [comment]
Does this also happen via flatpak?

**Comment by hhyyrylainen** [comment]
So far there's been only just that one report about this freezing on linux, and I've now successfully been using the launcher a bunch on Fedora without any issues. So this does seem pretty distro specific, which if flatpak is unlucky could mean that the flatpak runtime also experiences that. Though, this is soon becoming irrelevant as I'm rewriting the launcher entirely in C# with Avalonia framework.

**Comment by hhyyrylainen** [comment]
With the reimplemented launcher the file verify is done using C# data streams that hash the file as it is being downloaded. This issue should no longer be possible.
