### ISSUE TITLE
Unable to run ./CreateIcons.rb on Arco linux

### ISSUE THREAD

**Issue by LiquidZulu** [Revolutionary-Games/Thrive-Launcher#141]
Hello,

Upon cloning and installing I am unable to run `./CreateIcons.rb`, attempting this yields the following error:

```rb
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- os (LoadError)
	from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from ./CreateIcons.rb:5:in `<main>'
```

I have attempted removing `Thrive-Launcher` and re-installing it to no avail, after confirming that I do have the [git-lfs](https://archlinux.org/packages/community/x86_64/git-lfs/) package installed.

**Comment by hhyyrylainen** [comment]
` cannot load such file -- os (LoadError)`

is the interesting part. It means you are missing a ruby gem. I guess I'll need to mention that the gems that are needed for Thrive development are also needed here: https://github.com/Revolutionary-Games/Thrive/blob/master/doc/setup_instructions.md#ruby
