### ISSUE TITLE
Linux launcher opens centered in the wrong screen

### ISSUE THREAD

**Issue by XmakerenX** [Revolutionary-Games/Thrive-Launcher#152]
**Describe the bug**
When opening the launcher on Linux in a setup with multiple screens the launcher will always open centered in the left most screen 

**To Reproduce**
1. Have a Linux setup with multiple screens
2. Open the launcher
3. See that it will always open centered in the left most screen

**Expected behavior**
Expected behavior that the Launcher won't try to position itself and allow the window manager to do it

**Desktop:**
 - OS: Linux (Arch Linux with KDE Plasma 5 on X11)
 - Launcher version [1.3.0]

**Additional context**

**Comment by hhyyrylainen** [comment]
Happens to me too. The launcher uses electron framework which is based on Google Chromium browser. And that opens on the wrong screen for me as well, so basically this is a bug in chromium and the only thing we can do is update our used electron version once (if ever) there's a fix for this in there.

**Comment by hhyyrylainen** [comment]
With Avalonia now the launcher 2.0 opens on the right monitor for me.

**Comment by XmakerenX** [comment]
I tried Launcher 2.0.2  and can confirm it now open in the right monitor for me as well
