### ISSUE TITLE
Using system proxy

### ISSUE THREAD

**Issue by 84634E1A607A** [Revolutionary-Games/Thrive-Launcher#160]
Please note that you should only propose improvements to the **launcher** here. If you want to propose an improvement to Thrive itself head on over to [our forums](https://community.revolutionarygamesstudio.com/).

**Is your feature request related to a problem? Please describe.**
Sometimes we need a proxy (HTTP or SOCKS5) to assure high network speed & stable Internet connection. I cannot find the setting anywhere.

**Describe the solution you'd like**
Add an option to use system proxy, or just default use system proxy.

**Comment by hhyyrylainen** [comment]
I wonder if .NET does this automatically... If not this is still a valid feature request.

**Comment by 84634E1A607A** [comment]
Can confirm that .NET uses system proxy automatically.

**Comment by 84634E1A607A** [comment]
Can confirm that .NET uses system proxy automatically.
