### ISSUE TITLE
(Linux) Missing Libraries

### ISSUE THREAD

**Issue by Narotiza** [Revolutionary-Games/Thrive-Launcher#2]
In the right place this time, I apologize because I have no idea how to use giTHUB!!!! (of course, I'm still probably doing something wrong here!!!!)
I get this error whenever I try to launch Thrive 0.3.3 with the launcher. Last time I installed Thrive manually on Linux I had a similar issue with libraries and ended up having to place the missing ones in the bin folder in order for it to work.

Log:
`Playing Thrive 0.3.3
Thrive is running. Log output:
Process Started
ERROR: /home/narotiza/Downloads/thrive-launcher-linux-x64/installed/LINUX_Thrive-v0.3.3/Thrive-0.3.3/bin/Thrive: error while loading shared libraries: librtmp.so.1: cannot open shared object file: No such file or directory
child process exited with code 127`

**Comment by hhyyrylainen** [comment]
Commented here: https://github.com/Revolutionary-Games/Thrive/issues/513
