### ISSUE TITLE
api-ms-win-crt-runtime-l1-1-0.dll Error shows up when Launching game for first time on new computer

### ISSUE THREAD

**Issue by Amazonrazer** [Revolutionary-Games/Thrive-Launcher#20]
When i Run the game it waits a bit then shows up that
api-ms-win-crt-runtime-l1-1-0.dll was not found please try again or reinstall the game.
or something like that.
how can i solve it?

**Comment by hhyyrylainen** [comment]
That file should be included in the next release: https://github.com/Revolutionary-Games/Thrive/issues/539

**Comment by hhyyrylainen** [comment]
I think this should be fixed.
