### ISSUE TITLE
Launcher can not continue corrupted download

### ISSUE THREAD

**Issue by MkazemAkhgary** [Revolutionary-Games/Thrive-Launcher#27]
A download was corrupted and launcher gave me an error, some thing like "corrupted file and incorrect hash, please try again", i don't remember the exact message.

I had to go to 

    C:\Users\[USER_NAME]\AppData\Local\Temp\Revolutionary-Games-Launcher

and i saw `Thrive-0.4.1.0-WINDOWS-64bit.7z` file that had 0 size. i had to manually remove this file so the launcher could download it again.

I think this can be fixed fairly easily, just remove the temp file if download can not continue.

---

Launcher version: Thrive.Launcher-1.0.3-win.7z

**Comment by hhyyrylainen** [comment]
Deleting the downloaded file if the hash doesn't match was added. It should also fix this.
