### ISSUE TITLE
Make notification about not being able to download version info smaller

### ISSUE THREAD

**Issue by probonopd** [Revolutionary-Games/Thrive-Launcher#30]
Thanks for making an AppImage. However, according to the AppImage philosophy, please bundle everthing that is needed to run, so that on an offline machine we don't get

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/fcda10d44193d17c5e6bf6ce6ead7a5b10bf034f/database/Thrive_Launcher/screenshot.png)

Whatever it is trying to download here should be bundled inside the AppImage so that the AppImage does not need to download stuff.

Reference:
https://github.com/AppImage/appimage.github.io/pull/1628

**Comment by hhyyrylainen** [comment]
As the second button says, there is already a prepackaged version of the version data (`signed_versions.json`). Does it not work if you select to use the pre-packaged data?

It's not really feasible to bundle data for the game itself. So anyway the launcher needs to connect to the internet to download thrive versions. But it should be possible to play installed versions even without an internet connection.

**Comment by probonopd** [comment]
Can you make it use the pre-packaged data without showing that dialog?

**Comment by hhyyrylainen** [comment]
It would be possible but I want to get 0 bug reports from non-technical users complaining that their launcher doesn't show the latest version. Adding a note about the failed download somewhere in the UI would work. It takes a bit more work, though.

Also, I just noticed the incorrect font. It would be a good idea to bundle the used font as well.

**Comment by probonopd** [comment]
>  It would be a good idea to bundle the used font as well.

Definitely. :+1:

**Comment by hhyyrylainen** [comment]
The font should be now included: https://github.com/Revolutionary-Games/Thrive-Launcher/commit/05c50389106c1b9d47a1fe1c09cafaa9ecfa7a43
I'll rename and put this issue in the backlog.

**Comment by hhyyrylainen** [comment]
This was changed in launcher 2.0. Also I'd guess that this issue might be irrelevant now that we no longer have AppImage builds available. Let me know if this is still a problem in 2.0 and this can be reopened.
