### ISSUE TITLE
More readable file size for download modal.

### ISSUE THREAD

**Issue by Themayu** [Revolutionary-Games/Thrive-Launcher#36]
I think that converting the sizes shown in the download modal window (current and total file sizes) to a more human-readable format would be a good idea going forward, as the current solution of simply displaying the size in bytes does not seem very intuitive (is that the right word for it?).

For instance, when the download reaches 1,048,576 bytes transferred we should begin displaying it as "x.xx MB" instead of the raw byte count.

I feel that this, along with the percentage downloaded and (optionally) a display of the download speed (maybe estimated from the combined sizes of each chunk downloaded during the last second.) would make it a lot easier for users to estimate how long the download will take.

**Comment by hhyyrylainen** [comment]
Yes, these would be nice.
Maybe even a nice looking progress bar.
