### ISSUE TITLE
Apt update failure

### ISSUE THREAD

**Issue by billythakidd04** [Revolutionary-Games/Thrive-Launcher#44]
sudo apt update throws this error every time now.

```
Setting up thrive-launcher (1.1.1) ...
ln: failed to create symbolic link '/usr/local/bin/thrive-launcher': No such file or directory
dpkg: error processing package thrive-launcher (--configure):
 installed thrive-launcher package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 thrive-launcher
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by hhyyrylainen** [comment]
Did you have a previous version installed? Does it help if you uninstall and then reinstall?
I use [electron builder](https://www.electron.build/) to make the packages, so I can't really change anything about them, other than updating the electron builder version.

**Comment by billythakidd04** [comment]
I installed new only 2 days ago. I tried running `sudo apt remove thrive*` but got the nothing found error.

**Comment by hhyyrylainen** [comment]
Well I don't have `/usr/local/bin/thrive-launcher` on my system, but I'm using the rpm package.
I have no idea how to fix this, so I added the help wanted tag.

**Comment by Themayu** [comment]
How did you install the Thrive Launcher?

**Comment by hhyyrylainen** [comment]
Has this problem resolved itself, or is this still a problem? I'm thinking about closing this issue.

**Comment by billythakidd04** [comment]
I will try again this weekend. If it's not an issue I'll close it.

**Comment by hhyyrylainen** [comment]
I'll close this as no new comments came in, assuming that this is no longer a problem.
