### ISSUE TITLE
File Dialog formats result wrong on WIndows 11

### ISSUE THREAD

**Issue by nora2605** [Revolutionary-Games/Thrive-Launcher#512]
**Describe the bug**
On a fresh install of the Thrive launcher in Windows, changing the default install directory for the game results in the directory value being set to "file:///C:...". This causes a System.IO Exception when Installing or wanting to launch a game version.

**To Reproduce**
1. Install Launcher
2. Change install directory
3. Try to install the game

**Screenshots**
![grafik](https://github.com/Revolutionary-Games/Thrive-Launcher/assets/51268331/f6ea4583-1309-4dc5-a6e4-6d4ca9bc8923)
![grafik](https://github.com/Revolutionary-Games/Thrive-Launcher/assets/51268331/1686618c-3b44-49c4-8781-a1fb92b923f7)

Translated: The Syntax for the File, Directory or Volume Name is wrong.

**Desktop:**
 - OS: Windows 11, Canary Insider Build
 - Launcher version: 2.1.1

**Comment by nora2605** [comment]
Looking at the Code and doing some more experiments, this seems to be more of an Avalonia or Windows bug. Editing the config manually worked, I will close this since it's not related to Thrive specifically.

**Comment by hhyyrylainen** [comment]
Is there an open bug for Avalonia about this? If there is not, there's a chance that this is the "intended" folder selection dialog functionality and the Thrive Launcher would need to act accordingly on Windows.
