### ISSUE TITLE
On windows the launcher icon now has a black border in the taskbar

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive-Launcher#60]
for some reason. Should be investigated how to get it to look correct again.

**Comment by takko** [comment]
Just tested this on a second machine. Still fine.
So I guess this is a problem on your system. Maybe you have some icon cache problem: [Rebuild Icon Cache](https://www.thewindowsclub.com/rebuild-icon-clear-thumbnail-cache-windows-10?amp)

**Comment by hhyyrylainen** [comment]
Those instructions actually didn't work as they missed the crucial step of killing explorer.exe, so I had to get a different .bat file to do all the cleaning steps (including restart explorer)... and that had 0 effect on the taskbar icon, which is the only place that shows this problem. I'm now done experiencing the pain that is using windows for at least the next two months.

**Comment by vampycat237** [comment]
I am also noticing this issue, but only on launcher version 1.3.2. this screenshot has launcher installers 1.3.1 (top) and 1.3.2 right next to each other. not a huge change but noticeable. i can kind of see it in the taskbar too but in the icons the difference is much more noticeable.
![image](https://user-images.githubusercontent.com/98717915/195491542-a71c8de9-a1cd-42ae-b69e-8c2e8d3486f0.png)

**Comment by hhyyrylainen** [comment]
Making the launcher builds on Windows now seems to have fixed the icon (so maybe it was an ImageMagick problem that happened on Linux when working on .ico files).
