### ISSUE TITLE
'Failed to get content' error

### ISSUE THREAD

**Issue by Oliveriver** [Revolutionary-Games/Thrive-Launcher#7]
I opened the launcher for the first time in a while today and this happened:

<img src="https://i.imgur.com/rbAfgwO.png"/>

**Comment by hhyyrylainen** [comment]
I'm now getting that too. Looks like the development forum feed has changed so the launcher needs to be updated to compensate.

**Comment by hhyyrylainen** [comment]
Should be fixed by the latest commit
