### ISSUE TITLE
Missing 32 bit libs error catch doesn't work anymore

### ISSUE THREAD

**Issue by Anth0rx** [Revolutionary-Games/Thrive-Launcher#93]
I am experiencing an error when launching Thrive via the current Thrive-Launcher AppImage 1.2.4.

The error occurs as soon as ```Verifying archive 'Thrive_0.5.1.1_linux_x11.7z'``` reaches 100%.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/10292489/93591310-64dd3380-f9b0-11ea-876b-0ae7babe740e.png)

This issue is reproducible for older versions of Thrive lauched via the Thrive-Launcher as well.

**Comment by hhyyrylainen** [comment]
I assume you are running the AppImage release version.
So the error is that the 7zip executable that is bundled with the launcher is missing.
On my system when running the launcher like that the following is a valid executable: `/tmp/.mount_Thrive30QKzu/resources/app.asar.unpacked/tools/7zip/7za`

Could you check if that tmp folder mentioned in the error exists on your system when running the launcher? I'm going to guess that something is going wrong with the AppImage running on your system.
The rpm, deb, and raw zip versions will probably run even if the AppImage version doesn't

**Comment by Anth0rx** [comment]
Well, that's interesting: The directory and executable is definitely available:
```
-rwxrwxr-x. 1 root root 1638192 Aug  4 19:52 /tmp/.mount_Thriver6IEHd/resources/app.asar.unpacked/tools/7zip/7za
```

But when I try to run the file via the command line I get the following error:
```
zsh: no such file or directory: /tmp/.mount_Thriver6IEHd/resources/app.asar.unpacked/tools/7zip/7za
```

The `file` command tells me it's a 32-bit executable:
```
$ file /tmp/.mount_Thriver6IEHd/resources/app.asar.unpacked/tools/7zip/7za
/tmp/.mount_Thriver6IEHd/resources/app.asar.unpacked/tools/7zip/7za: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.0.30, stripped
```
That could be the cause of the error.

**Comment by hhyyrylainen** [comment]
Interesting. Now that you mention it, I remember adding advice for installing 32 bit libs on the ENOENT error, however it seems that the error doesn't get properly caught anymore, for some reason.

For reference here's the code that should catch errors: https://github.com/Revolutionary-Games/Thrive-Launcher/blob/5e4d0dc0712aa5ce66882485b594bb705fdafb91/src/play_handler.js#L186

Could you check the logs in `~/.config/Thrive Launcher/logs` to see if there is the full error callstack in there?
That would make fixing this much easier.
Though if, https://github.com/Revolutionary-Games/Thrive-Launcher/issues/56 is done first, this issue will be solved as well.

For now you should install 32 bit runtime libs to fix the problem.

**Comment by Anth0rx** [comment]
Thanks for the quick response. I also figured out that it has to do something with the 32 bit executable.

For now I installed p7zip on my system and made a symbolic link to the `/tmp/.mount_Thriver6IEHd/resources/app.asar.unpacked/tools/7zip/7za` file. That works for now.

Which runtime libs do I need to install?

**Comment by hhyyrylainen** [comment]
I'm not sure, it's distro specific. On Fedora, it should be enough to install `glibc.i686`.
For ubuntu the error suggestion info (that is currently broken), has this link: https://blog.teststation.org/ubuntu/2016/05/12/installing-32-bit-software-on-ubuntu-16.04/
